---
- name: Installer Apache sur les serveurs web
  hosts: webservers
  become: yes
  tasks:
    - name: Installer Apache (Debian/Ubuntu)
      yum:
        name: httpd
        state: present
        update_cache: yes
